### ISSUE TITLE
Current Portfolio Balance not updating 

### ISSUE THREAD

**Issue by michielveen** [bengmathew/tpaw#1]
Somehow my current portfolio balance is not being updated on a daily basis anymore. Not sure when it started, perhaps around the beginning of this month..

**Comment by michielveen** [comment]
It is working again.

**Comment by bengmathew** [comment]
Fixed it this morning. It was updating only till Aug 7.

**Comment by michielveen** [comment]
My portfolio estimate has not been updated since the weekend. Most likely it started after the last checking.

**Comment by bengmathew** [comment]
Thanks for reporting this. We changed a few things around deployments a few days ago and introduced this issue.  It should be fixed now.
