### ISSUE TITLE
Started With amounts August and September not correct 

### ISSUE THREAD

**Issue by michielveen** [bengmathew/tpaw#2]
Looks like Started With amounts of August and September are switched

**Comment by bengmathew** [comment]
Thanks for reporting this issue. It has been fixed. Please let me know if you continue to see any problems.

**Comment by michielveen** [comment]
After restarting the browser the initial issue is fixed but now the End With of September equals the end balance of the date the plan started in August (August 21 in my case) instead of the end balance of today (September 2)

**Comment by bengmathew** [comment]
Thanks. This should be fixed as well now.
