### ISSUE TITLE
Shiller's data until June

### ISSUE THREAD

**Issue by michielveen** [bengmathew/tpaw#4]
Not really a bug but there is an additional 3 months of data available on http://www.econ.yale.edu/~shiller/data.htm

Earnings: The ten year average real annual earnings of the S&P 500 from April 2013 to **March 2023** was $143.91. This data was obtained from the "US Stock Markets 1871 - Present and CAPE Ratio" spreadsheet available on Professor Robert Shiller's [website]

**Comment by bengmathew** [comment]
Thanks for the heads up. We've updated the data. The new data should show up on the website after the next S&P500 update (so after market close on Monday).

**Comment by michielveen** [comment]
Data until the end of 2023 available here https://shillerdata.com/

**Comment by bengmathew** [comment]
Thanks for the heads up. Data has been updated.

**Comment by michielveen** [comment]
Data until the end of Q124 available at https://shillerdata.com/

**Comment by bengmathew** [comment]
Thanks for the heads up. This update is a going to be a bit delayed. I expect to get it done in the first week of August.

**Comment by bengmathew** [comment]
The data has been updated.

**Comment by michielveen** [comment]
Hi, just curious if you will update Shiller data every 3 months. And as always, great tool!

**Comment by bengmathew** [comment]
As part of modeling expected return changes needed for duration matching, we are rewriting the code for processing Shiller's data. It will be easier to update the data after these changes are made. That will bring us close to Shiller's January release. So we're planning to skip the October update, and resume quarterly updating in January.

With these code changes, we are making it more seamless to update the data on our end, so we should be able to do it with less delays.

**Comment by bengmathew** [comment]
The data has been updated with Shiller's January release.

**Comment by michielveen** [comment]
I think an additional 6 months (compared to the last update) of Shiller data is now available. All the best.

**Comment by bengmathew** [comment]
Updated, thanks!
