### ISSUE TITLE
Adding saving after retirement date 

### ISSUE THREAD

**Issue by michielveen** [bengmathew/tpaw#6]
Hi,

Not 100% if I miss something but I it looks like if I cannot add an additional Savings entry after my retirement date.
Anything after that date highlights in red briefly and blocks.

**Comment by michielveen** [comment]
Forgot that this has to be entered as Income During Retirement

**Comment by bengmathew** [comment]
Yes, we forced income streams to be split up into pre and post retirement sections. It doesn't really make a difference for the math of the underlying model, but we felt that splitting it up this way would better match how people conceptually categorize their income flows.

I'm curious about whether you were trying to enter income that started before retirement and ended after retirement (i.e. the income spanned both pre and post retirement). Or did it start and end after retirement (i.e. the income is completely post retirement)?

**Comment by michielveen** [comment]
Hi, I was trying to model the sale of our house when we are ~ 80. So lumpsum inflow of cash and an increase of essential spending to cover the rent until end of retirement. I was curious of the impact on the current stock/bond split.
